### ISSUE TITLE
[Firefox 64+ only since 28.12.2018] Alternative searchbar script

### ISSUE THREAD

**Issue by pro100Hub** [Aris-t2/CustomJSforFx#10]
https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/alternative_searchbar.uc.js

@Aris-t2, thank you very much for the script, but i found some inaccuracies.
`var clear_searchbar_after_search = true;` only works with default search engines. When I type the text and select a search through another search engine, this request is processed only by the first engine from the list. Possible this be fixed?

Is it possible to replace the search engine switching instead of the ctrl+up/down key on the central mouse wheel? The idea is to switch search engines by scrolling and when you hover on the field of the search line or engine icon. I think it would be a better solution than using a keyboard.

**Comment by Aris-t2** [comment]
> only works with default search engines

`var clear_searchbar_after_search = true;` does not touch search engines at all, it just removes any input made into search box. Clicking on another 'oneoff search engine' from the list never changed the default engine and it states nowhere that my script  does this differently (and it is not planned, if you are going to ask).

`var revert_to_first_engine_after_search = true;` always reverts to the first engine in your search engine list. You can change the order within browsers search settings.

> Is it possible to replace the search engine switching instead of the ctrl+up/down key

No idea, this is what Firefox offers by default, I have not created this function.

**Comment by pro100Hub** [comment]
@Aris-t2 
Sorry, it seems you misunderstood me. English is not my native language, sorry again.
Please watch this [gif image](https://i.imgur.com/3YQc8A6.gifv).
When the function works `var clear_searchbar_after_search = true;`, then i can not use the search through other search engines in the drop-down box. This function is what it should be, but it requires some refinement.

> No idea, this is what Firefox offers by default, I have not created this function.

Maybe you can explain this idea to the user "[2002Andreas](https://www.camp-firefox.de/forum/memberlist.php?mode=viewprofile&u=51681)" and with its help will be able to implement this good idea in your script?

**Comment by Aris-t2** [comment]
This does not happen here. Clear startup/script cache or try a new browser profile with one testing https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/alternative_searchbar.uc.js file.

**Comment by pro100Hub** [comment]
> This does not happen here.

@Aris-t2 , unfortunately, this problem exists in the script.
This is also evidenced by this [comment](https://www.camp-firefox.de/forum/viewtopic.php?p=1100026&sid=f3c0dddaea255d260439d35969341370#p1100026) and [confirmation](https://www.camp-firefox.de/forum/viewtopic.php?p=1100027&sid=f3c0dddaea255d260439d35969341370#p1100027) from "2002Andreas".

**Comment by Aris-t2** [comment]
OK I can reproduce this issue now too. No idea why the script worked as expected before, but today it won't anymore. ;-)

**Comment by Aris-t2** [comment]
I have updated and changed the script, so the bug you mentioned should be gone.

One side effect is now the lost compatibility with Firefox 60-63, but I guess the "old search" covered that pretty good.

**Comment by pro100Hub** [comment]
> I have updated and changed the script, so the bug you mentioned should be gone.

Works amazingly! Low bow for you. Big Thanks! :1st_place_medal: :+1: 

Aris, my suggestion about switching search engines using the mouse wheel is still in force  :wink:. 
If in FF 64+ it is impossible to return the previous selection of search engines in any way, then switching using the mouse wheel will be a worthy replacement `old popup to switch engines`. Of course, I do not insist, this is just an offer and it will be at your discretion. The main thing is that the function "clear_after_search" is now working perfectly and thank you again for this. You are a terrific man :handshake:

**Comment by Aris-t2** [comment]
You can switch engines using mouse wheel while holding Ctrl key.

**Comment by pro100Hub** [comment]
> You can switch engines using mouse wheel while holding Ctrl key.

Hmmm, this is an interesting solution))
But maybe there is a way to use only the mouse without using the keyboard? For example, when we hover over a class `.searchbar-search-button` and scroll the wheel, the search engines will change.

**Comment by Aris-t2** [comment]
Yes, I pushed an update with a new option for that.
Keep in mind, this option uses internal search methods, so the popup appears when you switch an engine.

**Comment by pro100Hub** [comment]
> I pushed an update with a new option for that.

If there is no other way out, this is also a good way. Thank you!!! :handshake: :+1:

**Comment by Aris-t2** [comment]
Continue here: https://github.com/Aris-t2/CustomJSforFx/issues/11
There are new features present ;-)
