### ISSUE TITLE
movable-menu-button.uc.js lacks an icon

### ISSUE THREAD

**Issue by Madis0** [Aris-t2/CustomJSforFx#102]
Lets keep issue area clean and ask questions within the general discussion thread:
https://github.com/Aris-t2/CustomJSforFx/issues/29 (Firefox)
https://github.com/Aris-t2/CustomJSforFx/issues/30 (Thunderbird)

------------------------

Describe the issue:
https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/movable-menu-button.uc.js lacks an icon in Fx 120.0b8.

What should have happened instead?
Icon

Steps to reproduce the issue?
Install the js per instructions

Screenshots (drag and drop images into this post):
![Button](https://github.com/Aris-t2/CustomJSforFx/assets/8611110/97fa9cfe-ed63-4060-842e-9433755f6560)

System information
OS & OS version: Manjaro 23.1.0
Firefox or Thunderbird: Firefox
Firefox/Thunderbird version: 120.0b8
Firefox/Thunderbird theme: Themed with VivaldiFox

I worked around the issue with this userChrome css:
```
#movable-PanelUI-button .toolbarbutton-icon { /* Workaround for the movable-menu-button.uc.js via chrome://browser/skin/classic/browser/menu.svg */
    list-style-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" fill="context-fill" fill-opacity="context-fill-opacity"><path d="m13.375 4.25-10.75 0a.625.625 0 0 1 0-1.25l10.75 0a.625.625 0 0 1 0 1.25z"/><path d="m13.375 8.25-10.75 0a.625.625 0 0 1 0-1.25l10.75 0a.625.625 0 0 1 0 1.25z"/><path d="m13.375 12.25-10.75 0a.625.625 0 0 1 0-1.25l10.75 0a.625.625 0 0 1 0 1.25z"/></svg>') !important;
}
```

**Comment by Aris-t2** [comment]
I posted a new file using browser icon for the menu.
