### ISSUE TITLE
[Fx123] Search_engine_icon_in_searchbar - stopped working

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomJSforFx#108]
Describe the issue:
After update to Firefox 123 search icon reversed to standard glass icon  (module stopped working).
Reinstalling, clearing startup cache does not help 

What should have happened instead?
Module should replace icon of the search bar

Steps to reproduce the issue?
Activate Search_engine_icon_in_searchbar.
Observe the result

Screenshots (drag and drop images into this post):
![зображення](https://github.com/Aris-t2/CustomJSforFx/assets/32600318/903b8707-423d-41f6-bd63-af14a6276e6e)

![зображення](https://github.com/Aris-t2/CustomJSforFx/assets/32600318/03fa6dc7-41b3-4c5a-85bd-60343807dccc)

System information
OS & OS version: Win 10 x64
Firefox or Thunderbird: Firefox
Firefox/Thunderbird version: Firefox 123
Firefox/Thunderbird theme: default

**Comment by Aris-t2** [comment]
The issue is caused by the gone/deprecated call `document.getElementById("searchbar").currentEngine.iconURI.spec`.

I'm currently looking for the new way to get the icon.

**Comment by Aris-t2** [comment]
`document.getElementById("searchbar").currentEngine.getIconURL()` should work as a replacement.

**Comment by Aris-t2** [comment]
Get the updated file.

**Comment by Acid-Crash** [comment]
Hi all.
Reporting back.
The updated script does work as expected both on FF 123 and Nightly 125
![зображення](https://github.com/Aris-t2/CustomJSforFx/assets/32600318/c6f6cb16-662e-40d6-ad43-4e7387bcb948)

**Comment by Acid-Crash** [comment]
UPD. Found another bug.
For some reason when I activate Picture in Picture mode (In example this is Youtube) the icon becomes invisible.

![icon](https://github.com/Aris-t2/CustomJSforFx/assets/32600318/d2fab8a9-1973-42ae-9162-ffa7a1d46ab2)

You need to fully reload browser to restore it.

**Comment by Acid-Crash** [comment]
@Aris-t2 
The issue with the Picture in Picture mode is fixed now.
I will continue my observation for some time.
