### ISSUE TITLE
[Fx126] tabstoolbar_doubleclickontab_reloadtab.uc.js - stopped working

### ISSUE THREAD

**Issue by Haven667** [Aris-t2/CustomJSforFx#110]
### Describe the issue:

After the (manual) update from **Firefox v125.0.3** to the new **v126** the script **tabstoolbar_doubleclickontab_reloadtab.uc.js** doesn't reload the tab anymore.

### What should have happened instead?

Doubleclicking a tab should reload the page.

### Steps to reproduce the issue?

Make sure, that you have **tabstoolbar_doubleclickontab_reloadtab.uc.js** installed in Firefox!

1. Open Firefox.
2. Doubleclick a tab to reload the page.

### System information:

- OS & OS version: **Windows 10 19045.4355 (64-bit)**
- Firefox or Thunderbird: **Firefox**
- Firefox/Thunderbird version: **126.0 (64-bit)** - tested in a new, clean profile
- Firefox/Thunderbird theme: **Default**

**Comment by Haven667** [comment]
Hello,

I'm really not an expert regarding JS, but replacing `BrowserReload();` in **line 13** with `BrowserCommands.reload();` worked for me.

Regards

**Comment by Haven667** [comment]
Oh, sorry... I've overlooked the discussion discussion area.

**Comment by Aris-t2** [comment]
New file is up.

I'm busy with other non-Firefox things, so I don't check all of these places here as often as before.
