### ISSUE TITLE
Additional toolbars labels have unnecessary "(NULL)" suffix

### ISSUE THREAD

**Issue by Aleksandra0056** [Aris-t2/CustomJSforFx#112]
### Issue description:
The additional toolbars have the redundant suffix "(NULL)" in their names in the panel right-click context menu which also clutters the names.

### What should have happened instead?
The additional toolbars should have clear names without the suffix "(NULL)".

So, my solution is to fix it and remove the suffix "(NULL)" from their names.

### Steps to reproduce:
**IMPORTANT:** Make sure you have enabled the `additional_top_toolbars.uc.js` script before trying to reproduce the steps.
1. Open Firefox,
2. Right-click on navigation bar,
3. You see additional toolbar labels.

### Screenshots:
![Null label on additional toolbars](https://github.com/Aris-t2/CustomJSforFx/assets/69351811/eff91e76-d741-4f39-821b-3c5143252186)

### Additional attachments:
My additional_top_toolbars.uc.js script file:
[additional_top_toolbars.uc.js.txt](https://github.com/user-attachments/files/16068972/additional_top_toolbars.uc.js.txt)

### System informations:
OS & OS version: Windows 10 22H2 19045.4529 (64-bit)
Firefox or Thunderbird: Mozilla Firefox (64-bit)
Firefox/Thunderbird version: v127.0.2
Firefox/Thunderbird theme: [Firefox UI Fix](https://github.com/black7375/Firefox-UI-Fix) and [Activist – Soft](https://addons.mozilla.org/en-US/firefox/addon/activist-soft/)
Scripts loader: [Firefox Scripts](https://github.com/xiaoxiaoflood/firefox-scripts) (unofficial version by Onemen)

**Comment by Aris-t2** [comment]
Get the updated file.

Fx requires an acceleration key to be set in the code since version 127 (or earlier too?). In this case additional toolbars do not need any, so adding `toptoolbar.setAttribute("accesskey","");` fixes the issue.

**Comment by Aleksandra0056** [comment]
Okay, thanks! The issue has now completely disappeared.
