### ISSUE TITLE
Vertical Add-on Bar is probably using different colour setting than regular Add-on Bar uses

### ISSUE THREAD

**Issue by Aleksandra0056** [Aris-t2/CustomJSforFx#115]
### Describe the issue:
- Regular Add-on Bar is using "Background Colour" when trying to change colour in the **Firefox Colour** extension.
- However when I tried to change "Background Colour" to Vertical Add-on Bar, then it wasn't possible, because Vertical Add-on Bar is probably using different colour setting which can cause inconsistencies in certain themes.
- This would also lead the Vertical Add-on Bar to become glitched with tiled images instead of a single colour in certain themes like the Internet Explorer Blue Theme.

### What should have happened instead?
- My solution is to make the Vertical Add-on Bar use a "Background Colour" setting like a Regular Add-on Bar for consistent themes and colours.

### Steps to reproduce the issue?
I don't know how I would correctly or consistently write the reproduction steps, so I would skip this for this time.

#### When I try to change the Background Colour, then regular add-on bar follows the setting, but vertical not:
![Vertical Add-on Bar isn't using Background Colour like regular Add-on Bar](https://github.com/user-attachments/assets/3720c1fb-3bbd-4437-9072-fd4ec2d7aeee)

#### Mentioned tiled images bug when using IE Blue Theme:
![Tiled images issue](https://github.com/user-attachments/assets/0d6245f1-e91a-4ed6-817f-b17df4242d80)

### System information:
OS & OS version: Windows 10 22H2 19045.4717
Firefox or Thunderbird: Firefox
Firefox/Thunderbird version: 128.0.3

Firefox/Thunderbird theme:
- Internet Explorer Blue Theme (https://addons.mozilla.org/en-GB/firefox/addon/internet-explorer-blue-theme/)
- Firefox Colour extension (https://addons.mozilla.org/en-US/firefox/addon/firefox-color/)
- Firefox UI Fix (https://github.com/black7375/Firefox-UI-Fix)

By the way, I must say, that your scripts are so nice, that I can't use my Firefox without them. This project should deserve more attention and not only 230 stars, 22 forks and 16 watchers.

**Comment by Aris-t2** [comment]
Test the new file: https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/addonbar_vertical.uc.js

**Comment by Aleksandra0056** [comment]
> Test the new file: https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/addonbar_vertical.uc.js

Thank you! I'm closing this.
