### ISSUE TITLE
Vertical Add-on Bar is broken in customisation page after latest commit

### ISSUE THREAD

**Issue by Aleksandra0056** [Aris-t2/CustomJSforFx#116]
### Describe the issue:
I don't know what is causing this issue, but after the latest commit the Vertical Add-on bar is severely broken in the Customisation page

### What should have happened instead?
The Vertical Add-on Bar should work like before.

### Steps to reproduce the issue?
It is visible on the Customisation page.

1. Open Firefox,
2. Add some buttons to the Vertical Add-on Bar,
3. Exit Customisation page,
4. Re-open Customisation page.

### Screenshots:
![Screenshot 2024-08-05 173153](https://github.com/user-attachments/assets/acc1f83d-9d2a-40e4-8ce7-82039d744a71)

### System information
OS & OS version: Windows 10 22H2 19045.4717
Firefox or Thunderbird: Firefox
Firefox/Thunderbird version: v128.0.3
Firefox/Thunderbird theme: Firefox UI Fix - https://github.com/black7375/Firefox-UI-Fix

**Comment by Aris-t2** [comment]
Test the new file: https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/addonbar_vertical.uc.js

**Comment by Aleksandra0056** [comment]
Okay, now the issue disappeared, so I will close this.
