### ISSUE TITLE
Configuration Toolbar can contain items

### ISSUE THREAD

**Issue by Aleksandra0056** [Aris-t2/CustomJSforFx#117]
### Describe the issue:
- The Configuration Toolbar from the `space_and_separator_restorer.uc.js` script can contain items.
- I want only to note, that this behaviour is completely useless since the Configuration Toolbar doesn't normally appear in regular browsing, it only appears when the Customisation Firefox page is opened.
- It would also confuse some people who accidentally put their buttons on it because they could find these buttons for minutes until they found them ended in the Configuration Toolbar. I also lost a few of my buttons and found them on the Configuration Toolbar two days after I accidentally put them on the Configuration Toolbar.

### What should have happened instead?
So, I propose to remove this behaviour and make any items (except Space, Separator and Expanding space) unputtable on the Configuration Toolbar.

### Steps to reproduce the issue?
Do this:
1. Open Firefox,
2. Open Customise Firefox page,
3. Try to put items into the Configuration toolbar,
4. Close the Customise Firefox page and buttons will disappear until the page is reopened,
5. Re-open the Customise Firefox page and buttons will appear on the Configuration toolbar

### Screenshots (drag and drop images into this post):
![Screenshot 2024-08-05 195410](https://github.com/user-attachments/assets/4744a4dc-3ecd-422d-bb28-090dd1943c86)

### System information
OS & OS version: Windows 10 22H2 19045.4717
Firefox or Thunderbird: Firefox
Firefox/Thunderbird version: v128.0.3
Firefox/Thunderbird theme: Firefox UI Fix - https://github.com/black7375/Firefox-UI-Fix

**Comment by Aris-t2** [comment]
I can not "fix" this. Every attempt to permit adding items to the toolbar breaks everything on it. This was already the case back then, when this one was created. Use it "as is".

**Comment by Aris-t2** [comment]
No idea, I won't.

**Comment by Sneakpeakcss** [comment]
This can be done with pure css:

```css
#configuration_toolbar[draggingover],
#configuration_toolbar:has(toolbarpaletteitem[mousedown]) {
    pointer-events: none !important;
}
```
This works almost perfectly, but there's some weird behaviour where dragging over the toolbar has some magic pixel, somewhat connected to padding/margin, that causes flickering in certain locations.

```css
#configuration_toolbar {
  pointer-events: none !important;

  & > toolbarpaletteitem {
    pointer-events: auto !important;
    max-width: 100px !important;
  }

  &[draggingover],
  & > toolbarpaletteitem[dragover],
  &:has(toolbarpaletteitem[mousedown]) {
    pointer-events: none !important;
  }
}
```
This is more reliable, also fixes the 'flexible space' size to visible rectangle rather than the whole bar width.
