### ISSUE TITLE
[FX65] [Win] [M1]/[M2] Broken start home page with addonbar.uc.js

### ISSUE THREAD

**Issue by krystian3w** [Aris-t2/CustomJSforFx#12]
Lets keep issue area clean and ask questions within the general discussion thread:
https://github.com/Aris-t2/CustomJSforFx/issues/4

------------------------

## Describe the issue:

My home page do not run after update Firefox to 65 version.
Now I have blank new tab (similar to `about:blank`).

## What should have happened instead?

Should start my non-default website.

## Steps to reproduce the issue?

N/A

## Method used (M1 or M2):

M2, also glitch with M1.

## Screenshots (drag and drop images into this post):

N/A

## System information
OS & OS version:  Windows 7 x64 Pro SP1
OS theme: Windows Classic
DPI / HiDPI resolution:  DPI 120 / 125%
Firefox version: 65.0.0
Firefox theme: lw-theme 
Settings this issue occurs with:  

<ul> 

```js
// userChrome.js 
 userChrome.ignoreCache = true; 
 userChrome.import("/userChrome/addonbar.uc.js", "UChrm");
 userChrome.import("/userChrome/restart_button.uc.js", "UChrm");
 userChrome.import("/userChrome/restart_item_in_menu.uc.js", "UChrm"); 
 userChrome.import("/userChrome/alternative_searchbar.uc.js", "UChrm");
 userChrome.import("/userChrome/locationbar_popup_classic_with_two_lined_results.uc.js", "UChrm");
```
</ul>

**Comment by krystian3w** [comment]
```
//userChrome.import("/userChrome/addonbar.uc.js", "UChrm");
```

bug exsits in this file?

---

Also Mozilla no turn off complete XBL? I cannot use M1 or create broken path in xml file?

**Comment by Aris-t2** [comment]
Please make sure you are using the latest files and also run tests with a new profile.

The script works fine for me on Fx60-67.

Screenshot of Fx 65:
![123](https://user-images.githubusercontent.com/6013569/51969519-eba86a00-2474-11e9-9eb8-a005d0f04788.png)

Not sure about XBL, but I tested the alternative searchbar and the restart buttons scripts with method 1 on Fx 67 and they worked fine for me.

**Comment by krystian3w** [comment]
Try change home page to example `github.com` and try  run Firefox.

Also I check outdated script troubles.

**Comment by Aris-t2** [comment]
No change here, everything is still fine.

![01](https://user-images.githubusercontent.com/6013569/51970499-5eb2e000-2477-11e9-93db-e83300feadcd.png)
![02](https://user-images.githubusercontent.com/6013569/51970501-5fe40d00-2477-11e9-9d89-b20a63d671ad.png)

**Comment by krystian3w** [comment]
My `*.js` files should be latest, so I must use clean profile (not only refreshed).

Maybe extension glitch with `addonbar.uc.js`

**Comment by krystian3w** [comment]
On clean profile also glitch - opening blank new tab on e.g. `github.com`.

How works M2 / M1 with Firefox Portable by portable apps?

**Comment by Aris-t2** [comment]
I'm testing on Portable Firefox 65 x64 with M2. I have no add-ons/extensions installed and have not changed any default preferences while testing.

**Comment by krystian3w** [comment]
Also glitching after install Firefox x86 and add files `config*.js` for this version.

So no I must remove both Firefox instalation and backup profile, also try with Firefox portable.


if it does not work in a portable way, I think I will be testing a new user in Windows 7.

**Comment by krystian3w** [comment]
Firefox removed, Windows Registry cleaned by CCleaner and now I use MSI  Firefox 65 x64 installation and problem still exsist.

Maybe I use now workaround with recover last session automaticly, when load property last opened tab.

---


The strange thing is that it opens the second card normally as I create the entry of the start pages:

`github.com|github.com`

but first still broken and load `about:blank` or similar.

**Comment by Aris-t2** [comment]
I did like 30 restarts and only once this happens for me. Might be a Firefox startup cache glitch or a session bug or whatsoever.

Try to edit the js file and change

```js
setTimeout(function(){
  AddAddonbar.init();
},500);
```
to
```js
setTimeout(function(){
  AddAddonbar.init();
},2000);

```

**Comment by krystian3w** [comment]
OK, with longer delay firefox can load homepage, but what if suddenly the start page will try to load infinity and end up with a network error that is not available?

**Comment by krystian3w** [comment]
This is also slow down open pop-ups (
I see something charging him twice and the second approach loads the page in the pop-up.).

**Comment by krystian3w** [comment]
For me setTimeout `2000` ms is to huge, I open to many pop-ups on day.

**Comment by Aris-t2** [comment]
Try to set a lower value. Maybe `1000` is OK for your too.

**Comment by krystian3w** [comment]
"OK" long as no I use autostart firefox with Windows, when I must should use too much slow down ~`10000` and pop-ups when is unusable.

Workoarund is use task schedule to start Firefox after 2-3 minutes to Windows started.

**Comment by krystian3w** [comment]
Maybe

```js
// [!] Fix for WebExtensions with own windows by 黒仪大螃蟹 (for 1-N scripts)
```

helps on Addons and little of pop-ups, but still I need add set timeout lag 1000 - 4000 ms.

**Comment by xXJOKRXx** [comment]
> setTimeout(function(){

I tried this, When I open the browser my homepage loads but the browser displays nothing, and after 2 seconds it reloads and displays fine.

I guess that's considered a fix but the page has to load twice which is a side effect.

**Comment by xXJOKRXx** [comment]
> 
> 
> I did like 30 restarts and only once this happens for me. Might be a Firefox startup cache glitch or a session bug or whatsoever.
> 
> Try to edit the js file and change
> 
> ```js
> setTimeout(function(){
>   AddAddonbar.init();
> },500);
> ```
> 
> to
> 
> ```js
> setTimeout(function(){
>   AddAddonbar.init();
> },2000);
> ```

I tried this, When I open the browser my homepage loads but the browser displays nothing, and after 2 seconds it reloads and displays fine.

I guess that's considered a fix but the page has to load twice which is a side effect.

**Comment by Aris-t2** [comment]
Duplicating tab code was an old workaround for WebExtension windows. It was left inside current addonbar.uc.js by accident. 

I uploaded new files for all toolbar scripts. 

@xXJOKRXx 
@krystian3w 
Could you test the new scripts?

**Comment by xXJOKRXx** [comment]
Yes, I can confirm the new scripts work perfect now.
Well done. :)

**Comment by Aris-t2** [comment]
Continue here: https://github.com/Aris-t2/CustomJSforFx/issues/18
