### ISSUE TITLE
[Vertical Add-on Bar] Problem with badge string tilted 90 degrees to the right.

### ISSUE THREAD

**Issue by kiki-ja** [Aris-t2/CustomJSforFx#122]
@Aris-t2

addonbar_vertical.uc.js (2024/08/08)
Firefox 129.0.2, 130.0 C1 64bit
Windows 10 Pro 22H2 64bit

I am a fan of 'addonbar_vertical.uc.js'.

The screenshot shows an example badge for 'uBlock Origin'(addon).
After it was updated, I noticed that the badge string is tilted 90 degrees to the right.

Is it possible to move this back to horizontal as before?

　　![Vertical Add-on Bar - Badge-2](https://github.com/user-attachments/assets/2eed74f8-1a6e-4b23-8250-8d134ea01a9e)　　　　　　![Vertical Add-on Bar - Badge-3](https://github.com/user-attachments/assets/ca135802-d8e9-4174-b65d-789355d9a2dd)

------

I have made a few modifications as follows.
How about this?

```
#addonbar_v toolbarbutton .toolbarbutton-badge {
  writing-mode: horizontal-tb !important;
  margin-top: 0px !important;
  margin-bottom: -3px !important;
  padding-top: 0px !important;
  padding-bottom: 0px !important;
}
```

Thanks.
@kiki-ja

**Comment by Aris-t2** [comment]
I tried a different approach. Test the new file.

**Comment by kiki-ja** [comment]
@Aris-t2

**New: addonbar_vertical.uc.js (2024/09/03)**
Firefox 130.0 64bit, Theme: default system auto
Windows 10 Pro 22H2 64bit

config.js(install-folder)
https://github.com/alice0775/userChrome.js/blob/master/117/install_folder/config.js
config-prefs.js(install-folder/defaults/pref)
https://github.com/alice0775/userChrome.js/blob/master/117/install_folder/defaults/pref/config-prefs.js

uBlock Origin(addon) 1.59.0

------

I will tell you the result of my test.

[The badge string is now horizontal. But the right edge is cut off.]
　　![badge-04](https://github.com/user-attachments/assets/0a2343be-1ac1-4e04-91be-efbe1482ff2b)

[I changed the addonbar width from 30px to 40px with the same result.]
　　![badge-wide-02](https://github.com/user-attachments/assets/8f6d4714-b182-4ca2-9c54-178f9dee62f4)

[Badge strings are missing even with compact buttons.]
　　![badge-compact -02](https://github.com/user-attachments/assets/4c8e2b82-36b2-466b-bc34-b6f181179c3e)

Thank you for taking a different approach.
The initial adjustment matches in my environment.
I hope it will be helpful to other users.

　　![Vertical Add-on Bar - badge](https://github.com/user-attachments/assets/1d8cdbe3-861a-4723-8123-b189a4584f45)

@kiki-ja
