### ISSUE TITLE
Vertical add-on bar label have unnecessary "(NULL)" suffix

### ISSUE THREAD

**Issue by Aleksandra0056** [Aris-t2/CustomJSforFx#123]
### Describe the issue:
The vertical add-on bar has the redundant suffix "(NULL)" in its name in the toolbars menu on the Customise Firefox page.

### What should have happened instead?
The vertical add-on bar should have a clear name without the suffix "(NULL)".

So, my solution is to fix it and remove the suffix "(NULL)" from its name.

### Steps to reproduce:
**IMPORTANT:** Ensure you have enabled the `addonbar_vertical.uc.js` script before reproducing the steps.

1. Open Firefox,
2. Open Customise Firefox page,
3. Click on the toolbars button in the bottom panel,
4. You will see the Vertical add-on bar with the "(NULL)" label in the pop-up.

### Screenshots:

![Screenshot 2024-09-21 130709](https://github.com/user-attachments/assets/f0f92a5d-7258-4e0c-980d-69926fecc370)

### System information:
OS & OS version: Windows 10 19045.4894 (x64)
Firefox or Thunderbird: Firefox
Firefox/Thunderbird version: 130.0.1 (x64)
Firefox/Thunderbird theme: [IE Blue Theme](https://addons.mozilla.org/en-GB/firefox/addon/internet-explorer-blue-theme/) + [Firefox UI Fix](https://github.com/black7375/Firefox-UI-Fix)

**Comment by Aleksandra0056** [comment]
Okay, since the last commit of `addonbar_vertical.uc.js` it is fixed. I'm apologising, that I'm constantly bothering you with trivial issues, but I'm a perfectionistess and I'm reporting issues as a hobby. But it's true, that everything should be fixed.

I hope you have a nice day.

**Comment by Aris-t2** [comment]
Its OK for me. This is also just a hobby.
