### ISSUE TITLE
make addonbar_vertical.uc.js width fixed?

### ISSUE THREAD

**Issue by GoogleBeEvil** [Aris-t2/CustomJSforFx#13]
when change the width of side panel ,theaddonbar_vertical.uc.js will be also wider 
https://imgur.com/a/Bovjq3V

**Comment by Aris-t2** [comment]
OK, test the new version.

**Comment by GoogleBeEvil** [comment]
there is still a problem：if  narrow the sidepanel the icon in vertical bar will be overlapping with the history list

**Comment by GoogleBeEvil** [comment]
edit:while install the new version，custom  will make the browser weired

**Comment by Aris-t2** [comment]
Try the new update. ;-)
