### ISSUE TITLE
[WebExtension window] Blank page with multiple toolbar scripts active (e.g. add-on bar & vertical add-on bar)

### ISSUE THREAD

**Issue by GoogleBeEvil** [Aris-t2/CustomJSforFx#14]
open ublock original logger will open a blank window

**Comment by Aris-t2** [comment]
Add-on windows are not officially supported by these scripts.

There is however a workaround by aborix which I added to my toolbar scripts.
If you are using more, than one toolbar script, you have to remove the script addition from one file, e.g. from here (lines 65-74): https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/addonbar.uc.js#L65

**Comment by GoogleBeEvil** [comment]
I have tried delete 130-141
https://github.com/Aris-t2/CustomJSforFx/blob/34701c3640f8aad4cb961d41e4648328761bcaff/scripts/addonbar_vertical.uc.js#L130
but it didnt work.
there is interesting thing ,the old version 
https://github.com/Aris-t2/CustomJSforFx/blob/6eb443b3c1ca28c431d74bc89e286681c05c84cc/scripts/addonbar_vertical.uc.js didnt have this issue wheather delete aborix's fix or not

**Comment by GoogleBeEvil** [comment]
there is  still some issue."more than one scripts"  will break  some mini window(which usually do not have menubar,just a urlbar and  close button,sorry do  not know how to descript it)
https://addons.mozilla.org/en-US/firefox/addon/popup-tool/
https://www.youtube.com/watch?v=Bey4XXJAqS8

and a gif show a mini window opened by js not addon-window
https://imgur.com/a/VKxx2li
the two mini window   one is blank ,one is normal

**Comment by Aris-t2** [comment]
Sorry, but there is nothing we can do about mini windows right now.

**Comment by GoogleBeEvil** [comment]
doesnt work.still make mini window blank.hope mozilla dev toolbar api soon

**Comment by GoogleBeEvil** [comment]
http://tieba.baidu.com/p/6045112678
here is a workaround，maybe help：add this  to both uc.js  
init: function() {
**************
if (window.__SSi && window.__SSi !== 'window0') {
 return gBrowser.selectedBrowser.removeAttribute('blank');
}
*****************
}
@Aris-t2

**Comment by Aris-t2** [comment]
Thanks, I tested this and and it works for me.
Posted new files.

**Comment by GoogleBeEvil** [comment]
edit：https://github.com/Aris-t2/CustomJSforFx/issues/14#issuecomment-466639766  wont work in the new window created by dragging tab, it require to set browser.link.open_newwindow.restriction to 0 fixing this ,or just using `if (document.getElementById('main-window').getAttribute('chromehidden')) { return gBrowser.selectedBrowser.removeAttribute('blank');}` instead https://github.com/Aris-t2/CustomJSforFx/issues/14#issuecomment-466639766.

**Comment by Aris-t2** [comment]
So the script works fine now even without the old workaround.

**Comment by GoogleBeEvil** [comment]
emm，still an issue：
this time is  the addonbar.uc.js only.
If u click link from third software and call firefox start up,the page is blank.can u check the code,
i noticed the home page will flickering and scaled at the first time start.

**but  the vertical wont hava this issue**
![](https://i.imgur.com/MmJa354.gif)

**Comment by Aris-t2** [comment]
Looks like the link opens a window where "chromehidden" is empty (or at least different from the other WebExtension windows), but the code only triggers, if "chromehidden" attribute is not empty.

Can't tell you why the same code works in one script, but not inside an other script.

**Comment by GoogleBeEvil** [comment]
[WebExtension window] Blank page with add-on bar   script active.
 addonbar_v wont cause blank.
test the old version of addonbar, the same ,so probably not cause by the https://github.com/Aris-t2/CustomJSforFx/issues/14#issuecomment-466959012 code

**Comment by GoogleBeEvil** [comment]
https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/chrome/status-bar.uc.js
here is script that no mini blank、 no rescale home page.but it is useable only by the author's userchrome.js ,maybe load some  libs add by the author
can u port it to ordanay universal version load by  ardiman or Endor8's userchrome.js version

**Comment by Aris-t2** [comment]
You should be able too scripts from this collection to the method xiaociaoflood offers, since I can not reproduce most of the mentioned issues.

I also added xiaociaofloods method as "M3" to this project and mixed it with "M1", in case it works better or differently.

**Comment by krystian3w** [comment]
Workanoud no good works with Stylus - I lost url when create new stylesheet.

**Comment by Aris-t2** [comment]
Test the updated toolbar scripts.
Blank page on with new "normal/private" windows should be gone now too. The issue with WebExtension scripts was gone for a while now.

**Comment by Aris-t2** [comment]
Continue here: https://github.com/Aris-t2/CustomJSforFx/issues/18
