### ISSUE TITLE
JS to differentiate between read and unread tabs

### ISSUE THREAD

**Issue by zom243** [Aris-t2/CustomJSforFx#16]
It seems Firefox no longer differentiate between read and unread tabs (that opened with "open in new tab"). Now they have attribute `notselectedsinceload` but this attribute already not working since almost a year ago. The attribute value will always `true` whether the tab already read or not.

Then I found this JS to fix it
https://www.reddit.com/r/FirefoxCSS/comments/9foccv/tab_attribute_visitedtrue_or_just_visited/e5y3fus/

Maybe with the author permission you can incorporate it in your JS repo.

I don't know what's in Firefox dev's mind, they're ruining this great browser.

**Comment by Aris-t2** [comment]
I agree, this feature was useful and its "replacement" is worthless, but this project is not about collecting various scripts from other projects. ;-)

If the script would be on Github inside another Github project, I would add a link to it, but pointing to a Reddit thread, which points to another non-English download site is not a good way to point to other scripts.
