### ISSUE TITLE
[Fx66][M1] Multiple add-on bar appears after opening customizing mode

### ISSUE THREAD

**Issue by DavidXanatos** [Aris-t2/CustomJSforFx#17]
Describe the issue:
When addonbar.uc.js is enabled and one open the customization tab, additional toolbars appear one on top of the other and the customization tab closes again :/

What should have happened instead?
no redundant addon bars should be shown and the customization tab should not auto close

Steps to reproduce the issue?
install addonbar.uc.js using method 1 right click on the toolbar and choose customize

Method used (M1 or M2):
1

Screenshots (drag and drop images into this post):

System information
OS & OS version: win 10
OS theme: light
DPI / HiDPI resolution: 100%
Firefox version: 66.0.1
Firefox theme: defualt
Settings this issue occurs with: default

**Comment by Aris-t2** [comment]
This does not happen here. Test on a new browser profile and also test M2/M3.

![001](https://user-images.githubusercontent.com/6013569/54878690-471d2580-4e30-11e9-8848-d176fb316071.png)
![002](https://user-images.githubusercontent.com/6013569/54878691-471d2580-4e30-11e9-8031-5a65df62854a.png)

**Comment by Aris-t2** [comment]
Looks like this issue only happens with recent Firefox versions an method 1 (M1).
I just uploaded updated scripts.

**Comment by Aris-t2** [comment]
Does the new code work for you too?
