### ISSUE TITLE
[custom toolbars] blank toolbar / (home) page / (WebExtension) window

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomJSforFx#18]
Recent script updates fixed issues mentioned in[ [FX65] [Win] [M1]/[M2] Broken start home page with addonbar.uc.js](https://github.com/Aris-t2/CustomJSforFx/issues/12) and in [[WebExtension window] Blank page with multiple toolbar scripts active (e.g. add-on bar & vertical add-on bar)](https://github.com/Aris-t2/CustomJSforFx/issues/14).

Should those issues or similar toolbar script related issues occur again, this will be the place to talk about it.

**Comment by krystian3w** [comment]
Try open some link in incognito mode.

**Comment by Aris-t2** [comment]
Links open fine here in new private window and in new tabs inside private window. I even have all toolbat scripts active at once.

What happens on you end?

**Comment by krystian3w** [comment]
Now I have same results. 


I remind only, because recently I no noticed that there was a problem.

**Comment by GoogleBeEvil** [comment]
nice work

**Comment by Aris-t2** [comment]
This can be closed now.
