### ISSUE TITLE
Is it possible to autohide scrollbars?

### ISSUE THREAD

**Issue by sinankizar** [Aris-t2/CustomJSforFx#19]
Hello and thank you so much for the custom scrollbars script. 
This is not an issue. I am using it right now and it is gorgeous. As a mac user I wanted to hide the floating scrollbars when they are inactive as in OSX. Is it possible? I have searched the script to do that but I couldn't seem to find it. 

Firefox 66 on Windows 10

Thanks in advance.

**Comment by Aris-t2** [comment]
Scrollbars in Firefox can not be automatically hidden.

**Comment by sinankizar** [comment]
Thank you, i am loving my new scrollbars :)
