### ISSUE TITLE
restart_item_in_menu.uc.js with method 2?

### ISSUE THREAD

**Issue by krystian3w** [Aris-t2/CustomJSforFx#2]
## **Describe the issue**: 

Possible run `restart_item_in_menu.uc.js` with `method 2`?

## **What should have happened instead?**

File `restart_item_in_menu.uc.js` no add ementents to the 'aplication menu' and 'file menu' after restart browser.

## **Steps to reproduce the issue?**

[chrome.zip](https://github.com/Aris-t2/CustomJSforFx/files/2410599/chrome.zip) - unpack in firefox profile folder

[Mozilla Firefox.zip](https://github.com/Aris-t2/CustomJSforFx/files/2410609/Mozilla.Firefox.zip) - unpack to firefox instalation  folder

## **Method used (M1 or M2):** 

M2

## **Screenshots (drag and drop images into this post):**

N/A?

## **System information**
**OS & OS version:**  Windows 7 Pro x64
**OS theme:** Classic
**DPI / HiDPI resolution:**  125%
**Firefox version:** 62.0.2
**Firefox theme:** lw-theme
**Settings this issue occurs with:**  change name `restart_button.uc.js` to `restart_item_in_menu.uc.js`?

---

I tried use userChrome.js file: https://github.com/Aris-t2/CustomJSforFx/blob/40b1a7bd2674052f8ce6493313ab2859e5856456/method%202/profile/userChrome.js#L1-L4

but then even `restart_button.uc.js` did not work.

I tried to change name file in `config.js` file:

https://github.com/Aris-t2/CustomJSforFx/blob/40b1a7bd2674052f8ce6493313ab2859e5856456/method%202/firefox/config.js#L13

It did not help.

**Comment by Aris-t2** [comment]
I guess there is a misunderstanding. You cannot use `restart_item_in_menu.uc.js` the same way you can use `restart_button.uc.js` code inside config.js like I mentioned back then. You have to use either the full method 1 or 2 and add all files into the correct folders like mentioned on the main page.

1. From this projects `\method 2\profile\` folder copy `userChrome` folder and `userChrome.js` file to `\ PROFILENAME \chrome\` folder.

2. From this projects `\method 2\firefox\` folder copy `defaults` folder and `config.js` file to Firefox main directory (where the Firefox executable is). 

3. Copy `restart_item_in_menu.uc.js` to `PROFILENAME \chrome\userChrome\` folder.
Add `userChrome.import("/userChrome/restart_item_in_menu.uc.js", "UChrm");` line to `PROFILENAME \chrome\userChrome.js` file so it looks like
```js
 // userChrome.js 
 userChrome.ignoreCache = true; 
 userChrome.import("/userChrome/restart_item_in_menu.uc.js", "UChrm"); 
```

4. !!!IMPORTANT!!!
[Close Firefox and delete your script/startup cache or it won't work.](https://github.com/Aris-t2/CustomJSforFx#scriptstartup-cache-must-be-deleted-after-every-change)

**Comment by krystian3w** [comment]
OK, now is works - well `userChromeJS.js` is important file and save used script in `\chrome\userChrome.js` not in `config.js`.
