### ISSUE TITLE
Method 3 and custom profile location

### ISSUE THREAD

**Issue by rayman89** [Aris-t2/CustomJSforFx#20]
nevermind I've found the issue

**Comment by Aris-t2** [comment]
What was it?

**Comment by rayman89** [comment]
It wasn't working I thought it could be that the location of my profile folder was on the root folder since I don't install firefox I just unpack it and use a shortcut with ` -profile "profile/" -P "pro4" -no-remote`

but I later found out that when I downloaded the files from github some of them downloaded as an HTML instead of the real file and that was the problem.

BTW I used the author's instructions to install it since your instructions seems to differ with the creator and some files are different. You use the folder userChrome instead of just chrome  idk if firefox recognizes chrome and userChrome as the same but the config.js file points to a chrome folder not a userChrome folder `Cu.import(OS.Path.toFileURI(OS.Constants.Path.profileDir)+ '/chrome/utils/boot.jsm');.` Also the config-prefs.js you have on method 3 has the sandbox disabled `pref("general.config.sandbox_enabled", false);` which defeats the purpose of using method 3 over method 2.

**Comment by Aris-t2** [comment]
Sorry for the late answer. Seems I did not receive the automatic note from github back then.

> You use the folder userChrome instead of just chrome idk if firefox recognizes chrome and userChrome

My modified `userChrome.uc.js` gets loaded by m3 script and itself loads files from inside the subfolder `userChrome`. This change tries to keep scripts in a "subfolder" like the other methods.

And you are right about the sandbox pref, it should not be there. ;-)

**Comment by rayman89** [comment]
@Aris-t2 After the update to firefox 69 the scripts stopped working. I have set `toolkit.legacyUserProfileCustomizations.stylesheets;true` and updated the BootstrapLoader.jsm file. The rest of the userchrome modifications are working. Any ideas of what could be happening?

**Comment by Aris-t2** [comment]
`toolkit.legacyUserProfileCustomizations.stylesheets` only controls the loading of userChrome.css and userContent.css and is not relevant fur user JS scripts. Since those methods to load custom JS scripts are not written by me I can't tell, if their compatibility is broken or not. "Method 2" still works fine for me in latest 69 Nightly.

**Comment by Aris-t2** [comment]
Tested this on a new browser profile. I can't get m3 to work either.
Looks like m2 is the only one working atm.

**Comment by rayman89** [comment]
Is the syntaxis ok here to load multiple scripts? It only loads the download button for me

`// userChrome.js
userChrome.ignoreCache = true; // does not always work, so forget this better ;-)
userChrome.import("/userChrome/Buttons_restart.uc.js", "UChrm");
userChrome.import("/userChrome/Downloads_button.uc.js", "UChrm");`

**Comment by krystian3w** [comment]
For my M3 need also:

```
pref("general.config.sandbox_enabled", false);
```

in https://github.com/Aris-t2/CustomJSforFx/blob/master/method%203/firefox/defaults/pref/config-prefs.js, whitout any script no start.

Maybe I have mess/disorder/muddle in userChrome after test M1 an M2 in the past.
