### ISSUE TITLE
[Fx69+] Addonbar.uc.js and addonbar_vertical.uc.js - shotcuts broken

### ISSUE THREAD

**Issue by tortious** [Aris-t2/CustomJSforFx#21]
Lets keep issue area clean and ask questions within the general discussion thread:
https://github.com/Aris-t2/CustomJSforFx/issues/4

------------------------

Describe the issue:
I initially applied the addonbar_vertical.uc.js script to a fresh profile. It works well in every aspect except for the keyboard shortcut to toggle it. Confused, I eventually removed it and tried applying the addonbar.uc.js script (to see if the issue was exclusive to only one of them).

Again, same thing. It works except for the toggle. I also noticed this [script](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/master/Multirow%20and%20other%20functions/Other%20experimental%20features/Bookmarks-Toggle.uc.js) no longer works, either. Thus, it seems like there is something weird going on in relation to the keyboard shortcuts

What should have happened instead?
*ctrl* + *alt* + */* should toggle the visibility of the addonbar.vertical.uc.js script.

Steps to reproduce the issue?

Method used (M1 or M2):
Method 3

Screenshots (drag and drop images into this post):

System information
OS & OS version: Manjaro Linux 
OS theme: KDE Plasma 
DPI / HiDPI resolution: 1920x1080
Firefox version: Nightly (from the AUR)
Firefox theme: default
Settings this issue occurs with:

**Comment by Aris-t2** [comment]
Update to the new version of the scripts.
