### ISSUE TITLE
Method 1 in FF66+

### ISSUE THREAD

**Issue by MrFr1day** [Aris-t2/CustomJSforFx#23]
Hi,

I had to modify Method 1 to work with FF68, "extends" at line 8 in userChrome.xml should be changed to:
`extends="chrome://global/content/bindings/toolbarbutton.xml#toolbarbutton-badged">`

If anyone interested, I've also modified it to automatically load scripts without adding their names to the xml file (like Method 3):

```
var absolutePath = Components.stack.filename.substring(0, Components.stack.filename.lastIndexOf("/") + 1) + 'Scripts/';
					
var iterator = new OS.File.DirectoryIterator(OS.Path.fromFileURI(absolutePath), { winPattern: "*.js" } );
var promise = iterator.forEach(
	function onEntry(entry) { Services.scriptloader.loadSubScriptWithOptions(absolutePath + entry.name, {target: window, ignoreCache: true}); }
);

promise.then(
	function onSuccess() {
		iterator.close();
	},
	function onFailure(reason) {
		iterator.close();
		throw reason;
	}
);
```

BTW, Method 3 requires `pref("general.config.sandbox_enabled", false);`

Thanks.

**Comment by diamondavocado** [comment]
@MrFr1day Thanks for this. How did you find out how what you needed to change to get this working again? In case it happens again in the future if Mozilla changes stuff again.

**Comment by MrFr1day** [comment]
I didn't find that one, @Nuchi did (the developer of the project this method is based on).
https://github.com/nuchi/firefox-quantum-userchromejs/blob/master/userChrome.xml

In case this stops working, here is another one I'm using that seems to work as well:
`extends="chrome://global/content/bindings/general.xml#basecontrol">`

**Comment by Aris-t2** [comment]
Thanks , I added your solutions to the repository.

**Comment by krystian3w** [comment]
> BTW, Method 3 requires `pref("general.config.sandbox_enabled", false);`

for me too - https://github.com/Aris-t2/CustomJSforFx/issues/20#issuecomment-509035308 - cleaning profile and browser catalogs no help...
