### ISSUE TITLE
additional_top_toolbars start hidden

### ISSUE THREAD

**Issue by rayman89** [Aris-t2/CustomJSforFx#24]
@Aris-t2 
Is it possible to add something to the additional_top_toolbars.uc.js script to make the new toolbar appear as it was unticked / hidden / not showing when the browser starts or if that not possible would it be possible to create a key combination to hide/show it? Thank you.

**Comment by Aris-t2** [comment]
Sorry, I saw the post before, but did not have the time to answer yet:

Add to this line https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/additional_top_toolbars.uc.js#L52 this code:
`setToolbarVisibility(toptoolbar, false);` and top toolbars will always be collapsed on startup.

If you need a hotkey, try to adopt the code from "addonbar.uc.js" script: https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/addonbar.uc.js#L97

**Comment by rayman89** [comment]
Oh sorry I thought you were having problems with the notifications again. Thank you.

**Comment by rayman89** [comment]
> setToolbarVisibility(toptoolbar, false); 

Sadly it seems to not work anymore. Did the syntax change or something?

**Comment by rayman89** [comment]
@Aris-t2 
> setToolbarVisibility(toptoolbar, false); 

Sadly it seems to not work anymore. Did the syntax change or something?

Im using method 3

**Comment by Aris-t2** [comment]
I'm using method 2 on Nightly and it still works fine for me.

**Comment by rayman89** [comment]
I'm on 71b6 and the script is working but that part is not. Any ideas?

**Comment by Aris-t2** [comment]
I can confirm this.

**Comment by Aris-t2** [comment]
@rayman89 
I had to use a few workarounds, but the updated version works again.

**Comment by rayman89** [comment]
Thank you. Its working great now.
