### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by xlovinglyx** [Aris-t2/CustomJSforFx#25]
is there a code to have a status bar where i can inject customation panel icons in ff68 ?

**Comment by Aris-t2** [comment]
You can use the [add-on bar](https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/addonbar.uc.js) and add you buttons there, but there is no classic status shim present anymore. There are no add-on available for Fx57+ that would use it anyways...
