### ISSUE TITLE
Update for method 3

### ISSUE THREAD

**Issue by rayman89** [Aris-t2/CustomJSforFx#27]
They did answer me a few days ago about an update for method 3 to make it work again. I'll leave you the link if you wanna update it here as well

https://github.com/xiaoxiaoflood/firefox-scripts/issues/16

**Comment by Aris-t2** [comment]
Thanks.

**Comment by Orriky** [comment]
Unfortunately this fix doesn't work on Developer 70 according my tests

**Comment by Aris-t2** [comment]
Most scripts still worked in my test with Fx70 Nightly... Maybe there is a difference between Fx builds.

**Comment by peterwx** [comment]
It worked in 69 deved for me and still continues to work in Developer 70.

**Comment by stonecrusher** [comment]
Just adding that the [instructions](https://github.com/Aris-t2/CustomJSforFx#method-3---files-for-firefox-installation-and-profile-folders) also have to be updated.
It says you should copy a userChrome folder, but there is none.

**Comment by Aris-t2** [comment]
![image](https://github.com/user-attachments/assets/650570c0-11ce-475c-b887-379726aecf7d)
