### ISSUE TITLE
FF72 drops support for XBL, effectively killing Method1

### ISSUE THREAD

**Issue by glitsj16** [Aris-t2/CustomJSforFx#31]
Hi, I noticed https://bugzilla.mozilla.org/show_bug.cgi?id=1583314 is now in FF72. This means `Method1` is no longer working. In fact, https://github.com/nuchi/firefox-quantum-userchromejs confirms as much.

I've migrated to using Method3, which works fine on FF73.0b3 (developer edition), even **without** 'pref("general.config.sandbox_enabled", false);'.

Documentation should be updated to reflect this.

**Comment by Aris-t2** [comment]
Added note to main page. Thanks.
