### ISSUE TITLE
awesomebookmarkbar with FF78

### ISSUE THREAD

**Issue by nierewa** [Aris-t2/CustomJSforFx#35]
Lets keep issue area clean and ask questions within the general discussion thread:
https://github.com/Aris-t2/CustomJSforFx/issues/29 (Firefox)
https://github.com/Aris-t2/CustomJSforFx/issues/30 (Thunderbird)

------------------------

Describe the issue:

Hi. I hope I'm in the right place. If not, and it's not okay for me to post here, please just delete the request.

I would like to show and hide the bookmarks toolbar by pressing a hot key combination. I always had an AddOn "HideBookmarktoolbar" or something like that. Unfortunately this doesn't work with Quantum anymore.

So I searched for something and found the following script at ardiman: [awesomebookmarkbar](https://github.com/ardiman/userChrome.js/tree/master/awesomebookmarkbar)

The script no longer works. Unfortunately I don't get any support there.

Can anyone here help me and adapt the script or something?

Thanks in advance

Nierewa

Translated with www.DeepL.com/Translator (free version)

System information
OS & OS version: Windows 10
OS theme: 
DPI / HiDPI resolution: 
Firefox or Thunderbird: Firefox
Firefox/Thunderbird version: 78
Firefox/Thunderbird theme: 
Settings this issue occurs with:

**Comment by peterwx** [comment]
Maybe this one (different script) will work for you?
`Bookmarks-toggle.uc.js` script (findable on `github` search), this one is what i use (though not recently tested but should work), `F2` to toggle:
```javascript
// ==UserScript==
// @name           Bookmarks-toggle.uc.js
// @namespace      http://https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme
// @description    Bookmarks toolbar toggle on keydown
// @include        main
// @compatibility  Firefox 69
// @author         Izheil
// @version        27/05/2019 03:39 Added better compatibility with navigation toggler script
// @version        26/05/2019 10:19 Added a variable to change the key to press
// @version        25/05/2019 08:14 Added a compatibility fix for Firefox 67+
// @version        27/12/2018 15:05 Simplified the code
// @version        27/12/2018 15:05 Firefox 64
// ==/UserScript==
window.addEventListener("keydown", bookmarkToggle, false);

// If you want them to be visible by default, change this to true instead.
var bookBarStart = false,
// You can edit which key to press below. Make sure to encase the name between "" or '', and end the variable with a semicolon (;)
// You can't use ctrl, shift, alt, or CMD.
	keyPress = "F2";

if (bookBarStart == false) {document.getElementById("PersonalToolbar").style.visibility = "collapse";}
else {document.getElementById("PersonalToolbar").style.visibility = "visible";}

function bookmarkToggle(evt) {
	// Input the key you want to use here
    if (evt.key == keyPress && document.getElementById("PersonalToolbar").style.visibility == "visible") {
	 document.getElementById("PersonalToolbar").style.visibility = "collapse"}
	// Input the key you want to use here
	else if (evt.key == keyPress && document.getElementById("PersonalToolbar").style.visibility == "collapse") {
     document.getElementById("PersonalToolbar").style.visibility = "visible";

     var bookmarkItems = document.querySelectorAll("#PlacesToolbarItems .bookmark-item");
		  for (var i = 0; i < bookmarkItems.length; i++) {
		  	bookmarkItems[i].style.visibility = "visible";
		  }
	}
}
```

**Comment by nierewa** [comment]
Hi.

Thanks for your replay.
We solved it in this way:

`(function() {
    if (location != 'chrome://browser/content/browser.xul' && location != 'chrome://browser/content/browser.xhtml')
        return;
     let d1 = document.getElementById("PersonalToolbar");
         d1.style.visibility = "collapse";
    try {
        CustomizableUI.createWidget({
            id: 'bookmarkbar-button',
            type: 'custom',
            defaultArea: CustomizableUI.AREA_NAVBAR,
                onBuild: function(aDocument) {
                    var toolbaritem = aDocument.createXULElement('toolbarbutton');
                    toolbaritem.onclick = aEvent => onClick(aEvent);
                    var currentProfileDirectory = Services.dirsvc.get("ProfD", Ci.nsIFile).path.replace(/\\/g, "/");
                    var buttonicon = "bookmark.ico"
                    var props = {
                        id: 'bookmarkbar-button',
                        class: 'toolbarbutton-1 chromeclass-toolbar-additional',
                        label: 'Toggle',
                        tooltiptext: 'Toggle Bookmarktoolbar',
                        style: 'list-style-image: url("' + ("file:" + currentProfileDirectory + "/chrome/icons/" + buttonicon) +'");',
                    };
                    for(var p in props)
                        toolbaritem.setAttribute(p, props[p]);
                    return toolbaritem;
                }
        });
    } catch(e) {};


// Funktion zum Abfragen der Tastatur ("belauscht" Eingaben)
// Hinweis: Tasten, die anderweitig bereits "abgefangen" werden, ergeben keinen Event
document.addEventListener('keydown', (event) => {
        var keyName = event.key;


        // Funktion wird ausgeführt, wenn STRG + Alt + l gedrückt wird
        if (event.ctrlKey && event.altKey && keyName == 'l') {
           onClick();        
        }
    }, false
);



    function onClick(aEvent) {

        let d1 = document.getElementById("PersonalToolbar");
                     
        if (d1.style.visibility == "") {
            d1.style.visibility = "collapse";
        } else if (d1.style.visibility == "visible") {
            d1.style.visibility = "collapse";
        } else if (d1.style.visibility == "collapse") {
            d1.style.visibility = "visible";
        }
    }
})();`

With this one I've been able to use keyboard shortcut.

**Comment by Aris-t2** [comment]
Good to hear this could be solved.
