### ISSUE TITLE
Dropdown menu in google.com search results

### ISSUE THREAD

**Issue by radar54** [Aris-t2/CustomJSforFx#40]
Lets keep issue area clean and ask questions within the general discussion thread:
https://github.com/Aris-t2/CustomJSforFx/issues/29 (Firefox)
https://github.com/Aris-t2/CustomJSforFx/issues/30 (Thunderbird)

------------------------

Describe the issue:
in google search results, drop down menus do NOT drop down.  this is ONLY observed in a google results page

What should have happened instead?
the menu should drop down

Steps to reproduce the issue?
M1 - close firefox and reopen it and try again
M2 - restart firefox in Safe Mode and try again

Method used (M1, M2 or M3):
M1 and M2

Screenshots (drag and drop images into this post):
![google=firefox](https://user-images.githubusercontent.com/16638356/99154349-0e713600-267d-11eb-9f42-8037e73395b4.png)

System information
OS & OS version:   Windows 10 x64 bld 1909
OS theme: default theme
DPI / HiDPI resolution: 1920x1080
Firefox or Thunderbird:   firefox
Firefox/Thunderbird version:  82.0.3
Firefox/Thunderbird theme:   Classic Blue
Settings this issue occurs with:   any (tried in Safe Mode with no improvement)

**Comment by Aris-t2** [comment]
I have to mark this as non valid.

1. None of this projects scripts affect web sites.
2. You did not mention the script(s) you are using.
3. M1 should not be used on Fx 72+
4. Two methods should not be used at once.
5. I have many of this projects scripts active and can not reproduce this, not even on Fx 84 Nightly.

**Comment by radar54** [comment]
OK, thanks.  I guess that's what I wanted to find out:  if the scripts had any affect on the problem I am having.  For future reference, what do you man by M1 and M2, etc.  I thought M1 and M2 were the specific steps I took to reproduce the issue, but, based on your saying, "M1 should not be used on Fx 72+", maybe they mean something completely different.

**Comment by Aris-t2** [comment]
This project offers btw. offered three methods to get JavaScript to work. I labeled them M1-3.

In you case the issue is caused by something else. Try to clear temp. files and disable all add-ons / user scripts to find what is causing this.
