### ISSUE TITLE
Firefox Unbranded + WebExtensions Experiments?

### ISSUE THREAD

**Issue by lukaszpolowczyk** [Aris-t2/CustomJSforFx#42]
Why not [Firefox Unbranded](https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds) + WebExtensions Experiments?

https://webextensions-experiments.readthedocs.io/en/latest/basics.html
https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/basics.html

`about:config` flags work in Firefox Unbranded:
  * `xpinstall.signatures.required: false`
  * `extensions.legacy.enabled: true`

With WebExtensions Experiments you can prepare your own API and use it in extensions.

You can even try to get your own version of Firefox, with this additional API built and with switched about:config flags.

**Comment by Aris-t2** [comment]
Just a collection of scripts here. Not trying to create add-ons / web extensions.
