### ISSUE TITLE
editbookmarkspopup_expanded.uc.js shortcut

### ISSUE THREAD

**Issue by Orriky** [Aris-t2/CustomJSforFx#43]
Hi,

I use this script often.
It works well when I click on star bookmark toolbar icon, unfortunately it doesn't when I click "CTRL + D" shortcut.
Is it possible having bookmark panel expanded also in this case?

Thanks

**Comment by Aris-t2** [comment]
Test this: https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/editbookmarkspopup_expanded.uc.js

**Comment by Orriky** [comment]
Yes, it's perfect now

Thanks!!!
