### ISSUE TITLE
restart_button.uc.js and restart_item_in_menu.uc.js broken in FF92

### ISSUE THREAD

**Issue by nevubm** [Aris-t2/CustomJSforFx#45]
Describe the issue:
restart_button.uc.js and restart_item_in_menu.uc.js doesn't add restart button

What should have happened instead?
Should see restart button

Steps to reproduce the issue?
Install restart_button.uc.js and restart_item_in_menu.uc.js

Method used (M1, M2 or M3): M3

System information
Tested on Firefox 92 & Nightly 94, Windows

**Comment by Aris-t2** [comment]
Most likely method 3 is outdated.
M2 works fine here and was recently updated.
