### ISSUE TITLE
CustomJSforFx no longer works with Firefox 92

### ISSUE THREAD

**Issue by Wullfk** [Aris-t2/CustomJSforFx#46]
Hy,

I notice that after upgrading to Firefox 92, all the JS scripts I was using don't work anymore

The main scripts I was using
addonbar.uc.js
addonbar_vertical.uc.js
AutoSelectTab.uc.js
TabFocus.uc.js

Is there a solution? Otherwise I'll have to go back to the previous version of Firefox and block all updates

Thanks for the help you can give me

**Comment by Aris-t2** [comment]
You now have to use method 2 and its latest files. It was updated about about a month ago to work with Firefox 92.

Don't forget to delete the startupCache after updating method 2.

**Comment by Aris-t2** [comment]
Continue here: https://github.com/Aris-t2/CustomJSforFx/issues/29

**Comment by Wullfk** [comment]
> 
> 
> You now have to use method 2 and its latest files. It was updated about about a month ago to work with Firefox 92.
> 
> Don't forget to delete the startupCache after updating method 2.

OK thank's Aris

**Comment by peterwx** [comment]
More info on why only method 2 is working?
Can't `userscripts` be adapted to other methods in principle?

**Comment by Aris-t2** [comment]
Method 1 was "discontinued" after Mozilla removed XML bindings via CSS.

Method 3 is based on this project: https://github.com/xiaoxiaoflood/firefox-scripts
I did not have the change to look into recent changes/updates there to adopt them for this projects method 3 files.

Method 2 proved to be the most reliable in the past and only required minor tweaks to work with Fx 92+.
