### ISSUE TITLE
about_button.uc.js has no icon, no image

### ISSUE THREAD

**Issue by mimteatr** [Aris-t2/CustomJSforFx#48]
Lets keep issue area clean and ask questions within the general discussion thread:
https://github.com/Aris-t2/CustomJSforFx/issues/29 (Firefox)
https://github.com/Aris-t2/CustomJSforFx/issues/30 (Thunderbird)

------------------------

Describe the issue:
about_button.uc.js has no icon, no image! On the image below, button is placed between the restart_button on lef, (on red), and the minMaxCloseButton on the right at the corner but as you can see, actually you CAN'T see the button, but it is there!

What should have happened instead?
Have an image icon???

Steps to reproduce the issue?
Script loaded on FF

Method used (M1, M2 or M3):
M2

Screenshots (drag and drop images into this post): 
![image](https://user-images.githubusercontent.com/36078037/134009364-16b9d7b6-3531-41f0-bbd2-ddbc2f01163b.png)

System information
OS & OS version: Windows 10 Home 21H1 building 19043.1237
OS theme: Microsoft Windows "Life in Lavender"
DPI / HiDPI resolution: 1920 X 1080, 150% scaling
Firefox or Thunderbird: Firefox
Firefox/Thunderbird version: 93.0b7 (64-bit)
Firefox/Thunderbird theme: OceanReddit
Settings this issue occurs with: Always

**Comment by Aris-t2** [comment]
Do you have an up-to-date file?

The icon is present here even on Fx 94 for me.

Does the icon show up, if you paste this into location bar **chrome://global/skin/icons/defaultFavicon.svg** ?

**Comment by mimteatr** [comment]
Took it from here, isn't it the ONLY one available?
https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/about_button.uc.js

The icon do show up on chrome://global/skin/icons/defaultFavicon.svg, strange!

**Comment by Aris-t2** [comment]
There are two files, `about_button_generic.uc.js` and `about_button.uc.js`, but both point to `chrome://global/skin/icons/defaultFavicon.svg`.

To to redownload the file and to clear the [start-up cache](https://github.com/Aris-t2/CustomJSforFx#scriptstartup-cache-must-be-deleted-after-every-change).

**Comment by mimteatr** [comment]
Done and redone it all several times, no change. 

The about_button_generic.uc.js shows the icon but the about_button.uc.js doesn't.

**Comment by Aris-t2** [comment]
Alright, I will remove those lines from the file, but unless you don't mask your Firefox version as Firefox 86 or older, the code should not do anything.

**Comment by mimteatr** [comment]
I understand. 
I'm on FF beta and after today's update, strangely, it doesn't appear anymore, not even without icon! 

Maybe I placed it on a different toolbar inadvertently but entering in "customize tollbar" it doesn't show it anywhere. 
Where is it supposed to show by default? Maybe I'm not seeing well!
