### ISSUE TITLE
Nightly 65 broke bottom & vertical toolbars

### ISSUE THREAD

**Issue by Pizzapops** [Aris-t2/CustomJSforFx#5]
Describe the issue:

Both toolbars are missing after Nightly update 2018.10.23 Bottom toolbar shows but does not display any of the apps that were on it. Apps on those toolbars are available on the customize page. The configuration toolbar shows in customize but is not working. Spacer and separator cannot be dragged to another toolbar. The bottom toolbar shows at the top of the customize page but apps cannot be dragged to it.

I moved missing apps to the bookmarks toolbar. All of the other scripts seem to be working.

![2018-10-23_114815](https://user-images.githubusercontent.com/33039961/47378014-77636b00-d6bc-11e8-988d-e3d66f89a381.jpg)
![2018-10-23_121208](https://user-images.githubusercontent.com/33039961/47378226-1ab48000-d6bd-11e8-8f51-0edfdfd2f153.jpg)

System information
OS & OS version: Windows 10-64
Both CustomCSSforFx and CustomJSforFX are up to date.
Method used (M2)

**Comment by Aris-t2** [comment]
I just posted a compatibility update. Code no works with Fx60-65.
