### ISSUE TITLE
Instructions unclear for Linux users

### ISSUE THREAD

**Issue by bornagainpenguin** [Aris-t2/CustomJSforFx#53]
**Describe the issue:** Linux user is uncertain what is meant by: "copy defaults folder and config.js file to Firefox main directory (where the Firefox executable is"  Is the instruction intended to refer to `/lib/firefox/`? or to the main `/bin/` directory where there is a symbolic link for the Firefox binary which is linked to '/lib/firefox/'?  Some clarity would be appreciated.  Thanks.

**What should have happened instead?** Instructions should include clear path for Linux users.

**Steps to reproduce the issue?** Follow directions, come to the part where the path to the main directory is mentioned. Scratch head.

**Method used (M1, M2 or M3):** Was trying for M2 but confusion continues for all methods.

**Screenshots (drag and drop images into this post):**
![Screenshot at 2021-11-19 14-20-38](https://user-images.githubusercontent.com/82099949/142686782-59bdc38a-2a49-4a74-bacc-5f9ce7e7c6da.png)

**System information
OS & OS version:** Ubuntu-Mate 21.10
**OS theme:** Ambiant-Mate-Orange
**DPI / HiDPI resolution:**??? Whatever the default is.  Not sure what this has to do with a path location.

 
**Firefox or Thunderbird:** Firefox
**Firefox/Thunderbird version:** 94.0 64-bit
**Firefox/Thunderbird theme:** default...for now
**Settings this issue occurs with:** pre-settings.  This is a path location issue.

**Comment by BoomerangAide** [comment]
I suppose the instructions assume all systems create a shortcut in a menu or on the desktop or somewhere, and you can trace the location of the actually used executable through that. 
Or maybe through an equivalent of the task manager, this may be what I used for Firefox Portable since it got ```\AppFirefox\``` and ```\AppFirefox64\``` and I copied the files only in the 64 one.

**Comment by Aris-t2** [comment]
Linux folder/path structure is a huge mess for me. There are multiple paths with binaries and running the main one from any of them offers different results.

Look in about:support for "Application Binary".

I have three different locations on my Ubuntu VM:

Computer > snap > firefox > 731 > usr > lib > firefox 
Computer > snap > firefox > 747 > usr > lib > firefox 
Computer > snap > firefox > current > usr > lib > firefox

**Comment by Aris-t2** [comment]
Anything new here?
