### ISSUE TITLE
README M3 incorrect header status removal

### ISSUE THREAD

**Issue by peterwx** [Aris-t2/CustomJSforFx#56]
Lets keep issue area clean and ask questions within the general discussion thread:
https://github.com/Aris-t2/CustomJSforFx/issues/29 (Firefox)
https://github.com/Aris-t2/CustomJSforFx/issues/30 (Thunderbird)

------------------------

Describe the issue:
M3 header status text is [outdated].

What should have happened instead?
It should't have [outdated] in the header. I know it works and the description too says it.

Steps to reproduce the issue?
It's there in the README

Method used (M1, M2 or M3):
M3

Screenshots (drag and drop images into this post):

System information
OS & OS version: 
OS theme: 
DPI / HiDPI resolution: 
Firefox or Thunderbird: 
Firefox/Thunderbird version: 
Firefox/Thunderbird theme: 
Settings this issue occurs with:

**Comment by Speravir** [comment]
> Lets keep issue area clean and ask questions within the general discussion thread:

You did not. And by mentioning the general threads here you also left an automatic message there. Far from optimal.

> Describe the issue: M3 header status text is [outdated].
> 
> What should have happened instead? It should't have [outdated] in the header. I know it works and the description too says it.

I do not get it at all: What you call for is the active state since last change by Aris on 31 January: https://github.com/Aris-t2/CustomJSforFx/commit/a02b4e00304956b876e8eae4bbef8c2c88784e83.

**Comment by peterwx** [comment]
I did not mean to mention general discussion thread. Probably, just clicked "New Issue" on the wrong place.
Apologies for that.

On the last point, and so what that the last change was some months ago? M3 does works doesn't it? And the description is misleading?

**Comment by Speravir** [comment]
> I did not mean to mention general discussion thread. Probably, just clicked "New Issue" on the wrong place.

No this was not the problem.

> Was I supposed to delete some text from the template? I don't understand how I mentioned without doing actively such thing.

Aaah, yes. It comes from the template, I did not recognize this.

> On the last point, and so what that the last change was some months ago? M3 does work doesn't it? And the description is misleading?

In regards to this I must say sorry: I didn’t read carefully enough. So, you essentially say the claim method 3 being outdated is wrong.

I cannot confirm if you are correct, because I am using method 2 though not exactly like described here.

> And It's probably better to have this removed from other threads.

Not possible anymore.

**Comment by peterwx** [comment]
In regards to last 2 points:
Section header says "[outdated]" but right below in its description, the text says otherwise: "(up-to-date / works with Fx96+)".
I have numerous `userscripts` that to date work with M3 on Firefox Developer Edition(itself updated to most current version).

This discussion can't be removed from other threads, but maybe, at least, the template could have indications for removal at the end of sections, like, "please remove the above when creating issue" or "remove those which don't apply".

Thanks for your patience.

**Comment by Aris-t2** [comment]
The [outdated] tag is correct. I did not update this projects files to the recent ones provided on initial projects web site.

I saw reports of M3 files stopped working, so I marked them as "outdated".

M2 works as it should.

**Comment by peterwx** [comment]
That makes sense, in spite of [outdated] tag possibly creating some confusion as whether it's your M3 or the source that is outdated. 
I've been always using the source project for M3 and your scripts, so I've not experienced any problem.

Thanks.
