### ISSUE TITLE
[Github] Is it really a good idea to use "Discussions" instead of "Issues" ?

### ISSUE THREAD

**Issue by BoomerangAide** [Aris-t2/CustomJSforFx#64]
Hi,

Until now, if I visited after a while, in "Issues" I would sort by "Recently updated" then look at the issues order and the "updated on *DATE*" or "updated X hours ago" information, to have an idea of what changed since my last visit and is worth visiting.

In "Discussions", which seems to be an unfinished feature at this time, this is not possible.
The sort option is not present, and while it's apparently possible to cheat by typing "sort:updated-desc " in the internal searchbox (though I haven't confirmed if it work exactly as intended, and it may be a bug rather than a feature), it doesn't display the last update time like "Issues".

I personally think it would be better to revert to "Issues" for now, but that's my opinion.

**Comment by 2BeeOrNot** [comment]
I agree.

**Comment by Aris-t2** [comment]
I was under the impression a notification might be enough (at least in threads one participated in the past).

Discussions make at least direct replies easier.

![546566546546](https://user-images.githubusercontent.com/6013569/160145435-50f14f2b-403e-4502-8fc7-c853b91ed1ff.PNG)

**Comment by BoomerangAide** [comment]
> to have an idea of what changed since my last visit and is worth visiting.

Found a temporary partial workaround for that:
When using the "Top" sort thing and picking a date, it generates something like ```sort:top created:>=2022-03-20```.
Now I tried to change it to ```sort:top updated:>=2022-03-20 ``` and it worked (not 0 nor all topics appeared, and the topic had a message within the time specified.

Once again, I wish we had not moved stuff in **discussions** until devs of that feature realized they forgot to implement that properly (and who know what else).

**Comment by BoomerangAide** [comment]
You're answering something from 1 year ago, the sort type you talk about didn't exist back then, so discussions were largely inferior to issues to communicate and keep watch on progress on communication, thus not moving to discussions was better.

Even now that we have "sort by latest activity", this is still inferior to the similar option in Issues, that update the time display when sorted this way to the time of the last answer.
Moving back discussions to Issues is no longer as meaningful as back then, and no longer an option, but I still think it would have been better to not switch back then.
