### ISSUE TITLE
tabstoolbar_doubleclick_opennewtab.uc.js - not work for FF 63+ ?

### ISSUE THREAD

**Issue by pro100Hub** [Aris-t2/CustomJSforFx#7]
@Aris-t2, can you check please works of [this js script](https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/tabstoolbar_doubleclick_opennewtab.uc.js) at 63+?
I tested some of your other scripts and it works without problems, but this one does not want.
`Customizing mode > 'Titlebar' checkbox > unchecked` - done.

I also tried the [script from Endor8](https://github.com/Endor8/userChrome.js/blob/master/newtabbyleftclick/NewTabByLeftClick.uc.js), but it also does not work.

**Comment by pro100Hub** [comment]
Think i understood. Does this script work only on panels without focus on tabs? Can it be modified to open a new tab with the focus on the entire tabs panel?
Same principle: [GIF image](https://i.postimg.cc/gJydYmnw/2018-12-01-00-45-32.gif).

**Comment by Aris-t2** [comment]
Works fine here up to Firefox 65. Make sure you are double-clicking tabs toolbar not a tab or a button.

**Comment by pro100Hub** [comment]
> Works fine

Because of the large number of tabs, I did not understand how it works at first. After I understood and wrote about it in my second post. The script works only on the empty space of the tab bar without the participation of the tabs themselves.
Can you make adjustments to the script so that it works on the tabs too?

**Comment by Aris-t2** [comment]
@pro100Hub 
This should do the trick:

```js
var DoubleClickAnywhereOnTabsToolbar = {
  init: function() {
	  
	try {

 
      gBrowser.tabContainer.addEventListener('dblclick', function abcd(e) {
		if(e.button==0) {
			
			e.stopPropagation();
			e.preventDefault();
			
			BrowserOpenTab();

		}
	  }, true);
    
	
	} catch(e) {}

  }

}

setTimeout(function(){
  DoubleClickAnywhereOnTabsToolbar.init();
},500);

```

**Comment by pro100Hub** [comment]
@Aris-t2 

> This should do the trick:

Works wonderful! My low bow to you. You are a wonderful human. My handshake ;)
