### ISSUE TITLE
Some scripts don't work

### ISSUE THREAD

**Issue by Gersonzao** [Aris-t2/CustomJSforFx#72]
Describe the issue:
restart_button.uc.js
restart_item_in_menu.uc.js
restart_item_in_menu_old.uc.js

What should have happened instead?
The buttons should have appeared

Steps to reproduce the issue?
Normally install them

Method used (M1, M2 or M3):
M2

System information
OS & OS version: Windows 7 SP1 Build 7601
OS theme: Aero disabled
DPI / HiDPI resolution: 100%
Firefox or Thunderbird: Firefox
Firefox/Thunderbird version: 104.0.2
Firefox/Thunderbird theme: Any of them
Settings this issue occurs with: Any

**Comment by Aris-t2** [comment]
Still works fine here even on latest Nightly 106.

Try to setup a new clean browser profile for testing.

Only use those two:
restart_button.uc.js
restart_item_in_menu.uc.js

**Comment by Gersonzao** [comment]
> Still works fine here even on latest Nightly 106.
> 
> Try to setup a new clean browser profile for testing.
> 
> Only use those two: restart_button.uc.js restart_item_in_menu.uc.js

It works in a fresh profile

**Comment by Gersonzao** [comment]
By the way, I didn't change any settings in the new profile

**Comment by BoomerangAide** [comment]
Did you try the "Open folder" buttons for the "root folder" entry for each profile, and from whichever is the one with the "chrome" folder containing mods, copying said folder to the other profiles root folders? (brute force method)

**Comment by Gersonzao** [comment]
> Did you try the "Open folder" buttons for the "root folder" entry for each profile, and from whichever is the one with the "chrome" folder containing mods, copying said "chrome" folder to the other profiles root folders? (brute force method)

Yes

**Comment by Aris-t2** [comment]
@Gersonzao 

Any chance the startup cache might be the issue on your end?

https://github.com/Aris-t2/CustomJSforFx#scriptstartup-cache-must-be-deleted-after-every-change

**Comment by Gersonzao** [comment]
I've deleted it in every attempt I made. By the way, I'm using Firefox ESR (103.2) now

**Comment by BoomerangAide** [comment]
I'm on Firefox ESR 102.3.0esr 64 bits myself, and **restart_item_in_menu.uc.js** work for me, and I have changed almost nothing in the code.
I don't use the other, so I don't know about it. Are you sure you don't just have to move it/put it back after it was somehow removed with "customize toolbar" ?

**Comment by Gersonzao** [comment]
I'm sorry, I didn't understand that I needed to modify the paths inside `userChrome.js` and insert the name of the script. `restart_item_in_menu.uc.js` works perfectly now
