### ISSUE TITLE
Vertical addonbar and home button

### ISSUE THREAD

**Issue by Orriky** [Aris-t2/CustomJSforFx#78]
Hi,
I have a problem with the home button when I put it on addonbar_vertical.uc.js: it disappears after the browser restart.

**Comment by Orriky** [comment]
It happens only with the home button.
I created a new profile with only your script (I use xiaoxiaoflood loader) and it still disappears after a browser restart

**Comment by Aris-t2** [comment]
I can't say much about the other loaders current state, but I only test scripts using this projects "method 2" and it works in Firefox 110 and 112 Nightly.

Maybe you can see something in browsers error console, that points to an issue.

**Comment by Orriky** [comment]
I confirm, no problems with other methods.

Thanks
