### ISSUE TITLE
Firefox 113 an custom_scrollbars.uc.js

### ISSUE THREAD

**Issue by Endor8** [Aris-t2/CustomJSforFx#81]
In Firefox 113 Nightly your Script costum_scrollbars.uc.js not works any more. 
It hides only the scrollbars.
The reason should be this:   
https://bugzilla.mozilla.org/show_bug.cgi?id=1824236
See also this Thread on camp-firefox.de
https://www.camp-firefox.de/forum/thema/136152-scrollbar-uc-js-funktioniert-hier-im-nightly-nicht-mehr/?postID=1222789#post1222791
If you should have some time please take a look on it.
Thank you.
Best regards
Endor

**Comment by Aris-t2** [comment]
I doubt we can "fix" `custom_scrollbars.uc.js` for it to work on Firefox 113+ the way it did before, but we can try to recreate some parts of it.

After some test I could at least change some colors:
![image](https://user-images.githubusercontent.com/6013569/229155654-95c073d8-5a94-43f2-8e8d-e3977306a318.png)

Changing sizes (width/height) failed for me. Only default `scrollbar-width: thin !important;` changes it to a thin one.

![image](https://user-images.githubusercontent.com/6013569/229157253-3a987284-0b2a-4410-8098-6a5262e133dd.png)

**Comment by Aris-t2** [comment]
This file offers some results based on the old file. Settings that are not compatible are marked as "[!!!] not working in Fx 113+ [!!!]".

https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/custom_scrollbars_WIP_Fx113p.uc.js

**Comment by Endor8** [comment]
Hi Aris-t2
Thank you for the new Version it works. 
Special thanks from my god friend 2002Andreas from camp-firefox.de forum.
Best regards
Endor

**Comment by Aris-t2** [comment]
H Endor.

The idea behind this is based on this project description:

> From this projects \method 2\profile\ folder copy userChrome folder and userChrome.js file to \ PROFILENAME \chrome\ folder.

Scripts are placed inside `\chrome\userChrome\`, e.g. chrome\userChrome\custom_scrollbars.uc.js
Icons used by `custom_scrollbars.uc.js` can be placed inside 'icons' (sub)folder. I meant a subfolder inside \userChrome\ folder not just inside \chrome\ folder.

I see this can cause confusion, if someone adds images to `\chrome\icons\` by default.

**Comment by Endor8** [comment]
Hi Aris-t2
Thank you fore the explanation. The last Version 2.0.4 of this script works perfect.
Also in Firefox 114 beta and 115 Nightly.
       
Since i like the thumb rounded i added one option to round also the scrollbar-slider 
top and bottom , left and right.

This is the new option:
// default: cs_background_roundness = 0 / in px
const cs_background_roundness = 26;

and here i made the necessary changes:

scrollbar[orient="vertical"] slider {
background-image: ${cs_background_image_vertical} !important;
border-radius: ${cs_background_roundness}px !important;
}
scrollbar[orient="horizontal"] slider {
background-image: ${cs_background_image_horizontal} !important;
border-radius: ${cs_background_roundness}px !important;
}
 
Fore me so it looks better with rounded Thumbs.

Best regard
Endor
