### ISSUE TITLE
Nightly 115 - Method 2 stopped working

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomJSforFx#82]
Describe the issue:
After update to 115.0a1 (2023-05-13) (64-bit) all the JS scripts stopped working
I have updated all the files, cleared startup cache but this did not help
Here is the list of JS scripts I use

restart_item_in_menu.uc.js
editbookmarkspopup_expanded.uc.js

What should have happened instead?
JS scrips should work

Steps to reproduce the issue?
Install scrips via M2

Method used (M1, M2 or M3): M2

Screenshots (drag and drop images into this post):

System information
OS & OS version: Win10x64
OS theme: default
DPI / HiDPI resolution: 100
Firefox or Thunderbird: Firefox/Nightly
Firefox/Thunderbird version: 115.0a1 (2023-05-13) (64-bit)
Firefox/Thunderbird theme: default
Settings this issue occurs with: 
M2
restart_item_in_menu.uc.js
editbookmarkspopup_expanded.uc.js

**Comment by cadeyrn** [comment]
This is probably due to the removal of OS.File [1] which has long been known to happen.

[1] https://hg.mozilla.org/mozilla-central/rev/c698636dbfea

**Comment by Aris-t2** [comment]
True.

Substituting `OS.Path.toFileURI(OS.Path.join(OS.Constants.Path.profileDir`... with `PathUtils.toFileURI(PathUtils.join(PathUtils.profileDir`... works inside the actual user scripts, but fails for now, when used inside config.js or main.js/userChromeJS.js files.

**Comment by cadeyrn** [comment]
> works inside the actual user scripts, but fails for now, when used inside config.js or main.js/userChromeJS.js files

I think you're looking for:

`Cu.importGlobalProperties(['PathUtils']);`

**Comment by Aris-t2** [comment]
@Acid-Crash 

Forgot to ask, did you try the updated files.
cadeyrn provided a quick fix for a removed JavaScript module.

You need 
https://github.com/Aris-t2/CustomJSforFx/blob/master/method%202/profile/userChrome/userChromeJS.js
and
https://github.com/Aris-t2/CustomJSforFx/blob/master/method%202/firefox/config.js

**Comment by Acid-Crash** [comment]
Hi @Aris-t2 
Yes, I did try that.
It went a bit bumpy (did not work from the firs try). Maybe I have messed up something.
But when I tried it from scratch, it did the trick.

BTW. the links you shred give 404, but I have updated the files a bit earlier

**Comment by Acid-Crash** [comment]
@Aris-t2 Another question, during the update I have noticed the following line within
/profile/userChrome.js

`userChrome.ignoreCache = true;`
It is not present in the latest files, so I am curious why it was there in the first place and should I remove it?

**Comment by Aris-t2** [comment]
`userChrome.ignoreCache = true;` stopped achieving proper results and was removed a while back: https://github.com/Aris-t2/CustomJSforFx/commit/e17b800ef8fcfe60fb504244d84ebb9af30f3314
