### ISSUE TITLE
Nightly 117 - undo_closetab_button.uc.js stopped working

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomJSforFx#91]
Describe the issue:
It was noticed that in Nightly 117 undo_closetab_button.uc.js stopped working.
Other scrips do work (for example, editbookmarkspopup_expanded AND search_engine_icon_in_searchbar)
Updating all files within method + script files itself + clearing startup cache did not solve the issue

What should have happened instead?
New button element should show up

Steps to reproduce the issue?
Enable script, look for the new button

Screenshots (drag and drop images into this post):

System information
OS & OS version: Win 10x64
Firefox or Thunderbird: Firefox Nightly
Firefox/Thunderbird version: 117.0a1 (2023-07-10) (64-bit)
Firefox/Thunderbird theme: default

**Comment by Aris-t2** [comment]
Get new file(s). I just posted fixed versions.
