### ISSUE TITLE
Firefox 116 - custom_scrollbars.uc.js Arrow Version 2 not works.

### ISSUE THREAD

**Issue by Endor8** [Aris-t2/CustomJSforFx#97]
Hi Aris.
Windows 10 - Firefox 116 - 118

I and 2002Andreas from www.camp-firefox.de Forum
have noticed a small issue. If you chose Version 2
of the Arrows in line 76
const custom_scrollbar_arrows_version = 2;
there are no icons showing. 
With custom_scrollbar_arrows_version set to 1 ist works.
Of course the icon files are in the right folder.
Please take a look on it, if you have time.
The browser console says nothing related to this.

Thanks for your help.
Best regards
Endor

**Comment by Aris-t2** [comment]
Hi Endor, I could identify the issue. The image path required an additional `/`.

e.g.
`background-image: url("${ProfilePathChrome}icons/down.svg") !important;`
-->
`background-image: url("${ProfilePathChrome}/icons/down.svg") !important;`

Get the updated file here:
https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/custom_scrollbars.uc.js

**Comment by Endor8** [comment]
Hi Aris.
Thank you very much.
That fixes the issue.
Now every thing works fine again.
Best regards
Endor
