### ISSUE TITLE
About the Add-on button

### ISSUE THREAD

**Issue by beehiveharvest** [Aris-t2/CustomJSforFx#98]
Hello, I'm looking for a button for the Add-on Button.addon_buttons_in_overflow_menu

The above script doesn't seem to work, but without putting it directly in the overflow menu,

about_button
restart_button

It is possible to put the button in the overflow menu from there even if it appears in the toolbar, so are you planning to create a button that goes directly to the Add-ons page?

about:addons
page.

**Comment by beehiveharvest** [comment]
The attached figure is,

about_button
restart_button

in the overflow menu.

![SnapCrab_2023-09-02_18-01-22_No-0000](https://github.com/Aris-t2/CustomJSforFx/assets/82905681/8f5c2179-1414-4b4b-86ef-7b1239444080)

**Comment by Aris-t2** [comment]
To be honest I do not understand, what you are trying to achieve.

The script tries to take the full list from add-ons menu popup and attaches it to the overflow menu. At least one item has to be in overflow menu for it to appear.

![image](https://github.com/Aris-t2/CustomJSforFx/assets/6013569/b183a08d-b464-4ae4-b46f-c32affc21363)
![image](https://github.com/Aris-t2/CustomJSforFx/assets/6013569/6916a5cb-247c-4f93-acec-a7063cf4bbae)
![image](https://github.com/Aris-t2/CustomJSforFx/assets/6013569/f3486c3f-68d6-4820-b20d-16a583737b61)
