### ISSUE TITLE
[Fx117+] Expanding spacer isn't working correctly in menu bar

### ISSUE THREAD

**Issue by Aleksandra0056** [Aris-t2/CustomJSforFx#99]
### Describe the issue:
Expanding spacer in `space_and_separator_restorer.uc.js` isn't working correctly in menu bar, because it expands the space only to a half.

### What should have happened instead?
Expanding spacer should expand space in the entire menu bar.

### Steps to reproduce the issue?
Make you sure, that you have `space_and_separator_restorer.uc.js` installed in Firefox!

1. Open Firefox,
2. Enable menu bar,
3. Add some buttons next to “Help” button (which is located in menu bar),
4. Add an expanding spacer between the menu bar and buttons next to it.

### Screenshots (drag and drop images into this post):
![Expanding spacer isn't working correctly](https://github.com/Aris-t2/CustomJSforFx/assets/69351811/f169771b-cfac-4e6c-ae63-b3ac67a13e0a)

- Red arrow is pointing to actual position of buttons,
- Blue line is showing where these buttons should be located.

### System information
- OS & OS version: **Windows 11 22631.2265 (64-bit)**
- Firefox or Thunderbird: **Firefox**
- Firefox/Thunderbird version: **117.0 (64-bit)**, but it probably affects **118.0 Beta** and **119.0 Nightly**
- Firefox/Thunderbird theme: **Firefox UI Fix** (https://github.com/black7375/Firefox-UI-Fix) & **CustomCSSforFx** (https://github.com/Aris-t2/CustomCSSforFx).

**Comment by Aris-t2** [comment]
Actually that is supposed to happen. The menu already has a spacer:
![image](https://github.com/Aris-t2/CustomJSforFx/assets/6013569/a66de604-b1c1-41a3-bb1c-3f58ccc15db5)

Remove it using this CSS:
```css
#toolbar-menubar > spacer {
  display: none !important;
}
```

**Comment by Patricek0056** [comment]
Thank you, it worked! I'm proposing to keep this open, because other people maybe have this issue too, so they would see this workaround better.

By the way, can you tell me how can I enable the new Firefox View icon? I saw it in your screenshot, and it is better than the original orange icon. I don't want code for it, but I want to know if there exists `about:config` entry in Firefox 117.0, or it is only available on Nightly?

**Comment by Aris-t2** [comment]
The icon is the default one Nightly uses. You can not enable it through about:config.

I can add this to CustomCSSforFx for appmenu button on next update.

![image](https://github.com/Aris-t2/CustomJSforFx/assets/6013569/3ddd47f2-8e68-4184-a875-c8196758408c)

**Comment by Patricek0056** [comment]
I meant this icon.

![image](https://github.com/Aris-t2/CustomJSforFx/assets/69351811/0c34ca3d-8a98-45e8-9a63-001129340b39)

**Comment by mzso** [comment]
[**@Aris-t2**](https://github.com/Aris-t2) commented on [Sep 6, 2023, 7:06 PM GMT+2](https://github.com/Aris-t2/CustomJSforFx/issues/99#issuecomment-1708780300 "2023-09-06T17:06:08Z - Replied by Github Reply Comments"):
> Actually that is supposed to happen. The menu already has a spacer:
> https://github.com/Aris-t2/CustomJSforFx/assets/6013569/a66de604-b1c1-41a3-bb1c-3f58ccc15db5
> 
> Remove it using this CSS:
> ```css
> #toolbar-menubar > spacer {
>   display: none !important;
> }
> ```
> 
> _Originally posted by @Aris-t2 in https://github.com/Aris-t2/CustomJSforFx/issues/99#issuecomment-1708780300_

This doesn't seem to work for me (FF130).  The empty space on the right remains.
But I don't see any element there with DOMi.
